### ISSUE TITLE
Error: parsing config: found 0 items instead of 1

### ISSUE THREAD

**Issue by davidpirro** [gnojus/nec#4]
Hi,

I tried the program, but I get the error
```
Error: parsing config: found 0 items instead of 1
```

whenever I try to launch it.

I have a nextcloud account that is working and a local folder. The config file "nextcloud.cfg" is in the default location in ~/.config/Nextcloud

What am I doing wrong?

Thank you for your help!

**Comment by gnojus** [comment]
Hi,

looks like it fails to fetch your password.

What is your system? I assume it's linux, but which desktop environment and which credential manager?

**Comment by davidpirro** [comment]
hi,

thank you or your reply.

I'm on Debian stable. I'm using the awesome windowm and no credential manager.

**Comment by gnojus** [comment]
Thanks for the info.
> no credential manager  

hmm, it does seem to pick up some libsecret backend. Anyway,  I pushed a new version with minor fixes to password key lookup (you can use `nec update` to update). I doubt those will fix the problem, but now you can run it with `--debug` flag which will print more info. I should have done this a while ago.

If the problem persists, the contents of nextcloud config file and the output of [lssecret](https://github.com/gileshuang/lssecret) would be helpful. Both should not contain any actual plaintext secrets, but you may still want to censor out some sensitive details if any.

Last questions:  are you using email-password  login for nexcloud desktop client? And the client itself is installed normally, not via some sandboxed environment like snap of flatpack?

**Comment by davidpirro** [comment]
Hi,

unfortunately the problem is still there

here's the output with ```--debug``` flag:
```
2024/03/18 09:56:52 [nec] config keys: [0\Folders\1\ignoreHiddenFiles 0\Folders\1\journalPath 0\Folders\1\localPath 0\Folders\1\paused 0\Folders\1\targetPath 0\Folders\1\version 0\Folders\1\virtualFilesMode 0\authType 0\dav_user 0\displayName 0\serverVersion 0\url 0\user 0\version 0\webflow_user version]
2024/03/18 09:56:52 [nec] account "978853d4-7e44-102c-8dd5-a30fdf69fcfb" for "https://cloud.iem.at"
2024/03/18 09:56:52 [nec] reading password for "978853d4-7e44-102c-8dd5-a30fdf69fcfb:https://cloud.iem.at/:0"
2024/03/18 09:56:52 [keyring] Considering backends: [secret-service kwallet]
2024/03/18 09:56:52 [keyring] collections: ["" "Login"]
Error: parsing config: fetch password: libsecret: found 0 items instead of 1
```

the output of lssecret is:

```
Collection:	Login

Item:	Nextcloud
Key:	user
Value:	978853d4-7e44-102c-8dd5-a30fdf69fcfb_app-password:https://cloud.iem.at/:0
Key:	xdg:schema
Value:	org.qt.keychain
Key:	server
Value:	Nextcloud
Key:	type
Value:	base64

Item:	Nextcloud
Key:	user
Value:	XXX:https://cloud.iem.at/:0
Key:	xdg:schema
Value:	org.qt.keychain
Key:	server
Value:	Nextcloud
Key:	type
Value:	plaintext

Collection:	
```

and the content of the nextlcoud config file is

```
[General]
clientVersion=3.7.3git
confirmExternalStorage=true
newBigFolderSizeLimit=500
optionalServerNotifications=true
overrideLocalDir=
overrideServerUrl=
showCallNotifications=true
useNewBigFolderSizeLimit=true

[Accounts]
0\Folders\1\ignoreHiddenFiles=false
0\Folders\1\journalPath=.sync_30b1cd98816a.db
0\Folders\1\localPath=/home/YYY/ownCloud/
0\Folders\1\paused=false
0\Folders\1\targetPath=/
0\Folders\1\version=2
0\Folders\1\virtualFilesMode=off
0\authType=webflow
0\dav_user=978853d4-7e44-102c-8dd5-a30fdf69fcfb
0\displayName=YYY XXX
0\serverVersion=28.0.3.2
0\url=https://cloud.iem.at
0\user=@Invalid()
0\version=1
0\webflow_user=XXX
version=2

[Settings]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x3\xf4\0\0\x1\x9f\0\0\x5\xf7\0\0\x3\xb1\0\0\x3\xf4\0\0\x1\x9f\0\0\x5\xf7\0\0\x3\xb1\0\0\0\0\0\0\0\0\n\0\0\0\x3\xf4\0\0\x1\x9f\0\0\x5\xf7\0\0\x3\xb1)
```


the nextcloud client is install through apt, so "normally";)
thank you for your help!

**Comment by gnojus** [comment]
Thanks for the detailed info. Pushed a fix to use correct user name, should work now.

**Comment by davidpirro** [comment]
Thank you!

works now.

**Comment by Schplaf** [comment]
Hello,

Sorry to re-open this issue, but I encounter the same problem. My OS is Gentoo Linux, my WM is xmonad and I am not sure of what you call credential manager (gpg-agent ?).
I tried with the last release and with a version compiled from the source.  The error is exactly the same.

The output of nec --debug ls is : 
```
2024/08/21 18:52:42 [nec] config keys: [1\Folders\2\ignoreHiddenFiles 1\Folders\2\journalPath 1\Folders\2\localPath 1\Folders\2\paused 1\Folders\2\targetPath 1\Folders\2\version 1\Folders\2\virtualFilesMode 1\Folders\3\ignoreHiddenFiles 1\Folders\3\journalPath 1\Folders\3\localPath 1\Folders\3\paused 1\Folders\3\targetPath 1\Folders\3\version 1\Folders\3\virtualFilesMode 1\Folders\4\ignoreHiddenFiles 1\Folders\4\journalPath 1\Folders\4\localPath 1\Folders\4\paused 1\Folders\4\targetPath 1\Folders\4\version 1\Folders\4\virtualFilesMode 1\Folders\5\ignoreHiddenFiles 1\Folders\5\journalPath 1\Folders\5\localPath 1\Folders\5\paused 1\Folders\5\targetPath 1\Folders\5\version 1\Folders\5\virtualFilesMode 1\Folders\6\ignoreHiddenFiles 1\Folders\6\journalPath 1\Folders\6\localPath 1\Folders\6\paused 1\Folders\6\targetPath 1\Folders\6\version 1\Folders\6\virtualFilesMode 1\General\CaCertificates 1\authType 1\dav_user 1\displayName 1\serverColor 1\serverTextColor 1\serverVersion 1\url 1\user 1\version 1\webflow_CredentialVersion 1\webflow_oauth 1\webflow_user 2\Folders\44a3ffce-9121-42ca-91b3-6bb1a602845e\ignoreHiddenFiles 2\Folders\44a3ffce-9121-42ca-91b3-6bb1a602845e\journalPath 2\Folders\44a3ffce-9121-42ca-91b3-6bb1a602845e\localPath 2\Folders\44a3ffce-9121-42ca-91b3-6bb1a602845e\paused 2\Folders\44a3ffce-9121-42ca-91b3-6bb1a602845e\targetPath 2\Folders\44a3ffce-9121-42ca-91b3-6bb1a602845e\version 2\Folders\44a3ffce-9121-42ca-91b3-6bb1a602845e\virtualFilesMode 2\authType 2\dav_user 2\displayName 2\serverColor 2\serverTextColor 2\serverVersion 2\url 2\user 2\version 2\webflow_CredentialVersion 2\webflow_oauth 2\webflow_user version]
2024/08/21 18:52:42 [nec] account "XXX_MY_ACCOUNT" for "https://YYYY"
2024/08/21 18:52:42 [nec] reading password for "XXX_MY_ACCOUNT:https://YYY/:1"
2024/08/21 18:52:42 [keyring] Considering backends: [secret-service kwallet]
2024/08/21 18:52:42 [keyring] collections: ["" "Default keyring"]
Error: parsing config: fetch password: libsecret: found 0 items instead of 1
``` 

the output of lssecret is:

```
Collection:	

Collection:	Default keyring

Item:	
Key:	gkr:compat:hashed:xdg:schema
Value:	8c25a372fc9d481329cd3b67d601c285
Key:	gkr:compat:hashed:account
Value:	98f8e828fcedebb7a39a36e4005b8d5a
Key:	gkr:compat:hashed:service
Value:	186c2b5dde9e59cdfe39c9ef7c07c42b
Key:	xdg:schema
Value:	org.freedesktop.Secret.Generic
``` 

And I have installed Nextcloud with the package manager.

Regards,

**Comment by gnojus** [comment]
Hi, thanks for the bug report. From the logs it seems like nec is failing to pick up the correct keyring backend (it chooses libsecret, but I don't see any Nextcloud login info in the output).

Perhaps something changed with the way Nextcloud stores logins, or this was buggy in the first place. Anyway, I'll investigate and let you know.

**Comment by Schplaf** [comment]
Hello,

I have investigated a bit and I think solved it. I think the conjunction of my setup and the design of nextcloud caused the problem (and not nec at all).
To summarize:

- I do not use any desktop environment, therefore I don´t have the defaults tools from gnome (gnome-keyring for instance)
- I use pass+gnupg to handle my credentials 
- I did a fresh  install of nextcloud client, but it tried and failed to create a keyring that had to be the default one
- I installed seahorse (and dependencies), then I have created a keyring that  I set as the default one

Now, it looks like nextcloud, lssecret and nec are working as expected. However, it looks like nec sees only the first one of my two accounts.

**Comment by gnojus** [comment]
Thanks for the update. What makes you think nec only sees one account? Could you provide the output of nec with `--debug` of command that behaves such way?

**Comment by Schplaf** [comment]
Well, I may have misspoken: when I do nec ls, only shares from one of my accounts appear.

```
2024/08/23 14:12:15 [nec] config keys: [1\Folders\2\ignoreHiddenFiles 1\Folders\2\journalPath 1\Folders\2\localPath 1\Folders\2\paused 1\Folders\2\targetPath 1\Folders\2\version 1\Folders\2\virtualFilesMode 1\Folders\3\ignoreHiddenFiles 1\Folders\3\journalPath 1\Folders\3\localPath 1\Folders\3\paused 1\Folders\3\targetPath 1\Folders\3\version 1\Folders\3\virtualFilesMode 1\Folders\4\ignoreHiddenFiles 1\Folders\4\journalPath 1\Folders\4\localPath 1\Folders\4\paused 1\Folders\4\targetPath 1\Folders\4\version 1\Folders\4\virtualFilesMode 1\Folders\5\ignoreHiddenFiles 1\Folders\5\journalPath 1\Folders\5\localPath 1\Folders\5\paused 1\Folders\5\targetPath 1\Folders\5\version 1\Folders\5\virtualFilesMode 1\Folders\6\ignoreHiddenFiles 1\Folders\6\journalPath 1\Folders\6\localPath 1\Folders\6\paused 1\Folders\6\targetPath 1\Folders\6\version 1\Folders\6\virtualFilesMode 1\General\CaCertificates 1\authType 1\dav_user 1\displayName 1\serverColor 1\serverTextColor 1\serverVersion 1\url 1\user 1\version 1\webflow_CredentialVersion 1\webflow_oauth 1\webflow_user 2\Folders\44a3ffce-9121-42ca-91b3-6bb1a602845e\ignoreHiddenFiles 2\Folders\44a3ffce-9121-42ca-91b3-6bb1a602845e\journalPath 2\Folders\44a3ffce-9121-42ca-91b3-6bb1a602845e\localPath 2\Folders\44a3ffce-9121-42ca-91b3-6bb1a602845e\paused 2\Folders\44a3ffce-9121-42ca-91b3-6bb1a602845e\targetPath 2\Folders\44a3ffce-9121-42ca-91b3-6bb1a602845e\version 2\Folders\44a3ffce-9121-42ca-91b3-6bb1a602845e\virtualFilesMode 2\authType 2\dav_user 2\displayName 2\serverColor 2\serverTextColor 2\serverVersion 2\url 2\user 2\version 2\webflow_CredentialVersion 2\webflow_oauth 2\webflow_user version]
2024/08/23 14:12:15 [nec] account "XXX" for "YYY"
2024/08/23 14:12:15 [nec] reading password for "XXX:YYY/:1"
2024/08/23 14:12:15 [keyring] Considering backends: [secret-service kwallet]
2024/08/23 14:12:15 [keyring] collections: ["" "nextcloud_keyring"]
2024/08/23 14:12:15 [nec] account folder {/home/ZZZ/LOCAL_DIRECTORY -> /}
2024/08/23 14:12:15 [nec] account folder {/home/ZZZ/ANOTHER_DIRECTORY -> /ANOTHER_DIRECTORY}
  (list of folders)
2024/08/23 14:12:15 [nec] server response:
  (content of the server response -> OK)
``` 
However, nothing from  the  second account is listed.

**Comment by gnojus** [comment]
Oh, turns out folder ids are not limited to integers.
Try the new release (`nec update` if from github downloads).

**Comment by Schplaf** [comment]
It works perfectly now, great! I can see all my shared folders from my both accounts. Thank you very much!
